---
- name: Download WordPress
  get_url:
    url=https://wordpress.org/wordpress-5.1.1.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz  dest=/var/www/ copy=no


- name: Update default Apache site
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php




- name: COPY WP-CONFIG
  copy:
    src: "/home/project2/wp-config.php"
    dest: "/var/www/wordpress/"


- name: restart apache
  service: name=apache2 state=restarted


